import type { CSSProperties } from "react";

export const FONT = '"Inter", system-ui, sans-serif';
export const MONO = "ui-monospace, SFMono-Regular, Menlo, monospace";

export const pasteStyles = {
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    padding: "8px 16px",
    borderBottom: "1px solid #f4f4f5",
    background: "#ffffff",
  },
  field: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  label: {
    color: "#71717a",
    fontSize: 11,
    fontWeight: 500,
  },
  select: {
    border: "1px solid #e4e4e7",
    borderRadius: 8,
    background: "#ffffff",
    color: "#18181b",
    fontFamily: FONT,
    fontSize: 12,
    padding: "4px 8px",
  },
  seedInput: {
    width: 64,
    border: "1px solid #e4e4e7",
    borderRadius: 8,
    background: "#ffffff",
    color: "#18181b",
    fontFamily: FONT,
    fontSize: 12,
    padding: "4px 8px",
  },
  btnGroup: {
    display: "inline-flex",
    alignItems: "stretch",
  },
  groupButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 26,
    border: "1px solid #e4e4e7",
    background: "#ffffff",
    color: "#3f3f46",
    cursor: "pointer",
    padding: 0,
  },
  groupButtonPrimary: {
    background: "#18181b",
    borderColor: "#18181b",
    color: "#ffffff",
  },
  groupButtonDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  progress: {
    color: "#71717a",
    fontSize: 11,
    fontFamily: MONO,
  },
  tabStrip: {
    display: "flex",
    gap: 2,
    padding: "6px 12px",
    borderBottom: "1px solid #f4f4f5",
    flexShrink: 0,
  },
  tab: {
    border: "none",
    background: "transparent",
    color: "#71717a",
    fontFamily: FONT,
    fontSize: 12,
    fontWeight: 500,
    padding: "6px 8px",
    borderRadius: 8,
    cursor: "pointer",
  },
  tabActive: {
    color: "#18181b",
    background: "#f4f4f5",
  },
  panelScroll: {
    overflow: "auto",
    padding: 16,
    flex: 1,
    minHeight: 0,
  },
  panelEmpty: {
    padding: 32,
    color: "#a1a1aa",
    textAlign: "center",
    fontSize: 12,
  },
  metaStrip: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: 16,
  },
  tag: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: 999,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 500,
    background: "#f4f4f5",
    color: "#3f3f46",
  },
  tagSuccess: {
    background: "#ecfdf5",
    color: "#047857",
  },
  tagWarning: {
    background: "#fffbeb",
    color: "#b45309",
  },
  allClear: {
    color: "#047857",
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
  },
  errorGroup: {
    marginBottom: 20,
  },
  errorGroupTitle: {
    fontSize: 13,
    margin: "0 0 8px",
    fontWeight: 600,
  },
  count: {
    color: "#a1a1aa",
    fontWeight: 400,
  },
  errorList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  errorRow: {
    padding: 8,
    border: "1px solid #e4e4e7",
    borderRadius: 6,
    marginBottom: 8,
    minWidth: 0,
    overflowWrap: "anywhere",
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
  },
  errHead: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    minWidth: 0,
  },
  errComponent: {
    fontWeight: 600,
    fontFamily: MONO,
    fontSize: 12,
    overflowWrap: "anywhere",
  },
  errPath: {
    color: "#71717a",
    fontFamily: MONO,
    fontSize: 12,
    overflowWrap: "anywhere",
  },
  errMessage: {
    margin: "4px 0 0",
    fontSize: 12,
    overflowWrap: "anywhere",
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
  },
  errHint: {
    margin: "4px 0 0",
    fontSize: 12,
    color: "#1d4ed8",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
  },
  fatalCard: {
    border: "1px solid #fca5a5",
    borderRadius: 8,
    padding: 16,
    color: "#b91c1c",
    fontSize: 12,
  },
  fatalPre: {
    margin: "8px 0 0",
    fontFamily: MONO,
    whiteSpace: "pre-wrap",
  },
  renderPanel: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    overflow: "auto",
  },
  mockNote: {
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
    padding: "8px 16px",
    color: "#1d4ed8",
    background: "#eff6ff",
    fontSize: 12,
  },
  renderCanvas: {
    padding: 16,
    flex: 1,
  },
  renderDetails: {
    borderTop: "1px solid #f4f4f5",
    padding: "8px 16px",
    fontSize: 12,
    color: "#52525b",
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  treeHeader: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    border: "none",
    background: "none",
    cursor: "pointer",
    color: "inherit",
    font: "inherit",
    padding: "2px 0",
  },
  treeType: {
    fontFamily: MONO,
    fontWeight: 600,
    fontSize: 12,
  },
  treeProps: {
    margin: "0 0 0 24px",
    borderLeft: "1px solid #e4e4e7",
    paddingLeft: 10,
  },
  treeProp: {
    display: "flex",
    gap: 10,
    alignItems: "baseline",
    padding: "1px 0",
  },
  treeDt: {
    color: "#71717a",
    fontFamily: MONO,
    fontSize: 11,
    minWidth: 80,
    margin: 0,
  },
  treeScalar: {
    fontFamily: MONO,
    fontSize: 11,
    wordBreak: "break-word",
  },
  treeExpr: {
    fontFamily: MONO,
    fontSize: 11,
    color: "#1d4ed8",
  },
  treeExtra: {
    marginTop: 24,
  },
  treeExtraTitle: {
    fontSize: 13,
    margin: "0 0 8px",
  },
  treeJson: {
    fontFamily: MONO,
    fontSize: 11,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    margin: 0,
  },
  convergence: {
    padding: "8px 12px",
    borderRadius: 6,
    marginBottom: 16,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
  },
  convergenceOk: {
    background: "#ecfdf5",
    color: "#047857",
  },
  convergenceBad: {
    background: "#fef2f2",
    color: "#b91c1c",
  },
  traceTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 11,
    tableLayout: "fixed",
  },
  traceTh: {
    textAlign: "left",
    color: "#71717a",
    fontWeight: 500,
    padding: "2px 8px",
    borderBottom: "1px solid #f4f4f5",
  },
  traceTd: {
    padding: "2px 8px",
    borderBottom: "1px solid #f4f4f5",
    fontFamily: MONO,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  rowAppeared: {
    background: "#ecfdf5",
  },
  rowDropped: {
    background: "#fef2f2",
  },
  rootCell: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  helpOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(24, 24, 27, 0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
    padding: 24,
  },
  helpDialog: {
    background: "#ffffff",
    border: "1px solid #e4e4e7",
    borderRadius: 12,
    boxShadow: "0 16px 48px rgba(24, 24, 27, 0.18)",
    maxWidth: 560,
    width: "100%",
    maxHeight: "80%",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  helpHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderBottom: "1px solid #f4f4f5",
    fontWeight: 700,
    fontSize: 14,
  },
  helpBody: {
    padding: 16,
    overflowY: "auto",
    fontSize: 13,
    lineHeight: 1.55,
    color: "#3f3f46",
  },
  editorLock: {
    position: "absolute",
    bottom: 10,
    right: 10,
    background: "#f4f4f5",
    border: "1px solid #e4e4e7",
    borderRadius: 999,
    padding: "2px 10px",
    fontSize: 10,
    color: "#71717a",
  },
} satisfies Record<string, CSSProperties>;
