import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { oneLight, vscDarkPlus } from "react-syntax-highlighter/dist/cjs/styles/prism";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// The class CodeBlock puts on the SyntaxHighlighter root (PreTag="div").
const SCOPE = ".openui-code-block-syntax-highlighter";
const GENERIC_PRE = 'pre[class*="language-"]';

// Props whose bare numeric values are valid CSS without a unit.
const UNITLESS = new Set([
  "line-height",
  "opacity",
  "z-index",
  "font-weight",
  "flex",
  "order",
  "tab-size",
  "stroke-opacity",
]);

type PrismStyle = Record<string, Record<string, string | number>>;

const lightStyle = oneLight as unknown as PrismStyle;
const darkStyle = vscDarkPlus as unknown as PrismStyle;

function toKebab(prop: string): string {
  // The converted theme objects carry "Opacity" where the source CSS said "opacity".
  if (prop === "Opacity") return "opacity";
  return prop
    .replace(/^ms(?=[A-Z])/, "-ms")
    .replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function toValue(prop: string, value: string | number): string {
  if (typeof value === "number" && value !== 0 && !UNITLESS.has(prop)) {
    return `${value}px`;
  }
  // oneLight ships "hsl(0, 0, 95%)" — the unitless saturation is rejected by
  // future sass and warned on today.
  return String(value).replace(/hsl\((\d+), 0, /g, "hsl($1, 0%, ");
}

// Bare keys are token class lists ("comment", "atrule.rule"); the flat span
// output puts every class on one element, so they map to compound selectors.
function toCssSelector(key: string): string {
  if (key.startsWith(".") || key.startsWith(":")) return key;
  const firstWord = /^[a-z-]+/i.exec(key)?.[0] ?? "";
  if (firstWord === "pre" || firstWord === "code" || firstWord === "div" || firstWord === "span") {
    return key;
  }
  return firstWord === "token" ? `.${key}` : `.token.${key}`;
}

function scopeSelector(key: string): string | null {
  // Inline-code rule: the highlighter root here is a div, so
  // ":not(pre) > code" would wrongly match block code.
  if (key === ':not(pre) > code[class*="language-"]') {
    return null;
  }
  // The scope element is the PreTag itself, so pre-level rules target it directly.
  if (key.startsWith(GENERIC_PRE)) {
    return `${SCOPE}${key.slice(GENERIC_PRE.length)}`;
  }
  const selector = toCssSelector(key);
  // Pseudo-elements are not valid inside :where().
  const pseudo = /(::?(?:-moz-)?(?:selection|before|after))$/.exec(selector)?.[1] ?? "";
  const base = pseudo ? selector.slice(0, -pseudo.length) : selector;
  // :where() zeroes per-rule specificity so the dark blocks win purely by
  // source order (media default) or by the pinning attribute, never losing to
  // a more specific selector from the other theme.
  return `${SCOPE} :where(${base})${pseudo}`;
}

function emitRules(style: PrismStyle, prefix: string, indent: string): string[] {
  const out: string[] = [];
  for (const [key, decls] of Object.entries(style)) {
    const scoped = scopeSelector(key);
    if (!scoped) continue;
    out.push(`${indent}${prefix}${scoped} {`);
    for (const [prop, value] of Object.entries(decls)) {
      const kebab = toKebab(prop);
      out.push(`${indent}  ${kebab}: ${toValue(kebab, value)};`);
    }
    out.push(`${indent}}`);
  }
  return out;
}

const lines: string[] = [];
lines.push("// Auto-generated by src/scripts/generate-prism-themes.ts — do not edit manually.");
lines.push("");
lines.push("// Class-based prism themes for CodeBlock (useInlineStyles={false}).");
lines.push("// Light (oneLight) is the default; dark (vscDarkPlus) applies on");
lines.push("// dark-scheme devices unless light is pinned on :root, and wherever");
lines.push('// data-openui-mode="dark" is set.');
lines.push("");
lines.push(...emitRules(lightStyle, "", ""));
lines.push("");
lines.push("@media (prefers-color-scheme: dark) {");
lines.push(...emitRules(darkStyle, ':where(:root:not([data-openui-mode="light"])) ', "  "));
lines.push("}");
lines.push("");
lines.push(...emitRules(darkStyle, '[data-openui-mode="dark"] ', ""));
lines.push("");

const outputPath = path.resolve(__dirname, "../components/CodeBlock/prismThemes.scss");
fs.writeFileSync(outputPath, lines.join("\n"));
console.info(`Generated prismThemes.scss at ${outputPath}`);
