// Static snapshot of the home tweet wall, generated by scripts/fetch-static-tweets.mjs.
// Avatars/media live in public/tweets/ (downloaded by the script, no Twitter dependency).
// To refresh, or to change which tweets appear (edit the IDs in home-tweet-embeds.ts),
// run `pnpm fetch:tweets`. Generated file, do not edit by hand.
export type StaticTweet = {
  id: string;
  name: string;
  handle: string;
  verified: boolean;
  avatar: string;
  text: string;
  date: string;
  likes: number;
  replies: number;
  media?: { type: "photo" | "video"; url: string };
};

export const STATIC_TWEETS: StaticTweet[] = [
  {
    "id": "2031845364286783776",
    "name": "Chris Tate",
    "handle": "ctatedev",
    "verified": true,
    "avatar": "/tweets/avatar-ctatedev.jpg",
    "text": "@rabi_guha Very cool!",
    "date": "Mar 11, 2026",
    "likes": 30,
    "replies": 1
  },
  {
    "id": "2031989015147397122",
    "name": "rahulmax",
    "handle": "rahulmax",
    "verified": true,
    "avatar": "/tweets/avatar-rahulmax.jpg",
    "text": "@rabi_guha Been a fan of Thesys! The craft in UX and interaction is unmatched. Congrats! \n\nWas open-sourcing OpenUI always the plan, or did watching JSON break at scale across 10k+ devs force the shift to making the format a shared standard?",
    "date": "Mar 12, 2026",
    "likes": 0,
    "replies": 1
  },
  {
    "id": "2031891607394664677",
    "name": "jinjingliang",
    "handle": "JinjingLiang",
    "verified": true,
    "avatar": "/tweets/avatar-JinjingLiang.jpg",
    "text": "@rabi_guha Just tried it. Pretty cool",
    "date": "Mar 12, 2026",
    "likes": 9,
    "replies": 0,
    "media": {
      "type": "video",
      "url": "/tweets/media-2031891607394664677.jpg"
    }
  },
  {
    "id": "2034082798051443052",
    "name": "shadcn",
    "handle": "shadcn",
    "verified": true,
    "avatar": "/tweets/avatar-shadcn.jpg",
    "text": "@rabi_guha Looks great. Will give it a try. 👀",
    "date": "Mar 18, 2026",
    "likes": 26,
    "replies": 1
  },
  {
    "id": "2034668122691735612",
    "name": "LangChain JS",
    "handle": "LangChain_JS",
    "verified": true,
    "avatar": "/tweets/avatar-LangChain_JS.jpg",
    "text": "AI just built a full dashboard UI… while thinking🤔\n\nWe added @thesysdev’s OpenUI to @LangChain  frontend docs 👀 with a live demo.\n\nAsk an agent for a report → watch it stream:\n• KPI cards\n• charts\n• tables\n• structured layouts\nNo templates. No hardcoded components.\nJust",
    "date": "Mar 19, 2026",
    "likes": 43,
    "replies": 3,
    "media": {
      "type": "video",
      "url": "/tweets/media-2034668122691735612.jpg"
    }
  },
  {
    "id": "2034668644115107891",
    "name": "Christian Bromann",
    "handle": "bromann",
    "verified": true,
    "avatar": "/tweets/avatar-bromann.jpg",
    "text": "I am very bullish on OpenUI (openui.com) .. it comes with great components out of the box, streaming protocol is super efficient and has a super small footprint!\n\nAlso .. very easy to put together with @LangChain_JS 🚀",
    "date": "Mar 19, 2026",
    "likes": 58,
    "replies": 3
  },
  {
    "id": "2039548793960681815",
    "name": "AB",
    "handle": "abhin_27",
    "verified": false,
    "avatar": "/tweets/avatar-abhin_27.jpg",
    "text": "Thanks @rabi_guha! For me, OpenUI Lang is the unlock - the absurdly token efficient standard. So many possibilities when you're shipping full component trees over the wire. Excited to keep contributing to its growth!",
    "date": "Apr 2, 2026",
    "likes": 3,
    "replies": 0
  },
  {
    "id": "2032387346616758375",
    "name": "Pere",
    "handle": "pmontp19",
    "verified": false,
    "avatar": "/tweets/avatar-pmontp19.jpg",
    "text": "These guys cooked. How does it work? They build an AST from all OpenUI Lang statements response, compile the library's JSON Schema into a param catalog to map args to props, validate fields, then React walks the element tree calling each component's render function recursively",
    "date": "Mar 13, 2026",
    "likes": 13,
    "replies": 0
  },
  {
    "id": "2034284259805176222",
    "name": "Yasuhiro Yokota@タイミー",
    "handle": "yktyshr",
    "verified": false,
    "avatar": "/tweets/avatar-yktyshr.jpg",
    "text": "Generative UIのライブラリ OpenUIのPlaygroundさわれる\nopenui.com/playground",
    "date": "Mar 18, 2026",
    "likes": 8,
    "replies": 0,
    "media": {
      "type": "photo",
      "url": "/tweets/media-2034284259805176222.jpg"
    }
  }
];
