// Shared with the Gateway landing page. Rates are monthly equivalents;
// annual billing is selected by default on both pages.
export const GATEWAY_PLANS = [
  {
    name: "Free",
    monthly: 0,
    annualMonthly: 0,
    calls: "3K",
    overage: "—",
    note: "Bring your own LLM key",
    description: "For individuals exploring OpenUI Cloud with core limits.",
    features: [
      "3K API calls per month",
      "Bring your own LLM key",
      "Style customizations and popular LLM support",
      "Discord community support",
    ],
    cta: "Get started for free",
    href: "https://console.thesys.dev/keys",
  },
  {
    name: "Build",
    monthly: 59,
    annualMonthly: 49,
    calls: "25K",
    overage: "$0.002/call",
    note: "Email support",
    description: "For small teams shipping their first AI features.",
    features: [
      "Everything in Free",
      "25K API calls per month",
      "$0.002 per call after",
      "Higher request priority and rate limits",
      "Email support",
    ],
    cta: "Generate API key",
    href: "https://console.thesys.dev/keys",
  },
  {
    name: "Grow",
    monthly: 599,
    annualMonthly: 499,
    calls: "500K",
    overage: "$0.001/call",
    note: "SSO/SAML, priority support",
    description: "For businesses scaling production AI workloads.",
    features: [
      "Everything in Build",
      "500K API calls per month",
      "$0.001 per call after",
      "Highest request priority and rate limits",
      "Priority support and solutions engineering",
      "SSO/SAML",
    ],
    cta: "Generate API key",
    href: "https://console.thesys.dev/keys",
  },
  {
    name: "Scale",
    monthly: null,
    annualMonthly: null,
    calls: "Custom",
    overage: "—",
    note: "Self-hosting and VPC, SLAs",
    description: "For enterprises needing control over infrastructure, data, and models.",
    features: [
      "Everything in Grow",
      "Self-hosting or VPC deployment",
      "Custom rate limits and usage controls",
      "Compliance, SLAs, and support guarantees",
    ],
    cta: "Contact sales",
    href: "https://zcal.co/t/thesys/demo",
  },
] as const;
