// Shared with the Gateway landing page. Rates are monthly equivalents;
// annual billing is selected by default on both pages.
export const GATEWAY_PLANS = [
  {
    name: "Free",
    recommended: false,
    monthly: 0,
    annualMonthly: 0,
    calls: "3K",
    overage: "—",
    note: "Validate before users see it",
    features: [
      "3K responses/month",
      "Repair invalid output before it reaches users",
      "Bring your own LLM key",
      "Use any supported model",
      "Discord community support",
    ],
    cta: "Try Gateway free",
    href: "https://console.thesys.dev/keys",
  },
  {
    name: "Build",
    recommended: true,
    monthly: 59,
    annualMonthly: 49,
    calls: "25K",
    overage: "$0.002/call",
    note: "Repair + usage visibility",
    features: [
      "Everything in Free",
      "25K responses/month",
      "Automatic repair included",
      "Provider fallbacks during outages",
      "Usage, cost, and correction reporting",
      "Higher request priority and rate limits",
      "Email support",
    ],
    cta: "Start building",
    href: "https://console.thesys.dev/keys",
  },
  {
    name: "Grow",
    recommended: false,
    monthly: 599,
    annualMonthly: 499,
    calls: "500K",
    overage: "$0.001/call",
    note: "Lower rates, SSO, support",
    features: [
      "Everything in Build",
      "500K responses/month",
      "Cut overage to $0.001 per call",
      "Highest request priority and rate limits",
      "Priority support and solutions engineering",
      "SSO/SAML",
    ],
    cta: "Start scaling",
    href: "https://console.thesys.dev/keys",
  },
  {
    name: "Scale",
    recommended: false,
    monthly: null,
    annualMonthly: null,
    calls: "Custom",
    overage: "—",
    note: "Your cloud, your controls",
    features: [
      "Everything in Grow",
      "Run in your VPC or self-host",
      "Custom rate limits and usage controls",
      "Compliance and audit support",
      "SLAs and 24/7 support",
    ],
    cta: "Talk to sales",
    href: "https://zcal.co/t/thesys/demo",
  },
] as const;
