name: Build Python

on:
  push:
    branches: [ main ]
    paths:
      - py/**
  pull_request:
    branches: [ main ]
    paths:
      - py/**

defaults:
  run:
    working-directory: py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            py/.venv
            py/stream/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: make install

      - name: Run checks
        run: make ci
