name: Publish PyPI package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish'
        required: true
        type: choice
        options:
          - crayon_stream

defaults:
  run:
    working-directory: py

jobs:
  build:
    runs-on: ubuntu-latest
    # Required for OIDC token
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached Poetry dependencies
        uses: actions/cache@v3
        with:
          path: py/${{ inputs.package }}/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        working-directory: py/${{ inputs.package }}
        run: poetry install

      - name: Build package
        working-directory: py/${{ inputs.package }}
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: py/${{ inputs.package }}/dist/
